Mushrooms = read.csv(file="http://course1.winona.edu/bdeppa/DSCI%20415/Data/Mushrooms.csv",header=T)
names(Mushrooms)
head(Mushrooms)
summary(Mushrooms)
dim(Mushrooms)
mush.mat = Mushrooms[,-c(1,12,17)]
require(cba)
mush.dummy = as.data.frame(as.dummy(mush.mat))
implot(as.matrix(mush.dummy))
summary(pr_DB,"long")
require(MASS)
mush.dist = dist(mush.dummy,method="Jaccard")
summary(mush.dist)
mush.MDS = cmdscale(mush.dist,k=2)
plot(mush.MDS[,1],mush.MDS[,2],type="n")
text(mush.MDS[,1],mush.MDS[,2],labels=as.character(Mushrooms[,1]),col=as.numeric(Mushrooms[,1])+2,cex=0.8)
mush.iso = isoMDS(mush.dist,k=2)
plot(mush.iso$points,type="n")
text(mush.iso$points,labels=as.character(Mushrooms[,1]),col=as.numeric(Mushrooms[,1])+2,cex=0.8)